### ISSUE TITLE
Array index out-of-bounds error

### ISSUE THREAD

**Issue by Jugheadbomb** [Mikusch/friendlyfire#11]
Happens sometimes and only with `DHookCallback_CTFProjectile_Flare_Post`

```cpp
L 03/09/2024 - 09:18:40: [SM] Exception reported: Array index out-of-bounds (index -1, limit 8)
L 03/09/2024 - 09:18:40: [SM] Blaming: friendlyfire.smx
L 03/09/2024 - 09:18:40: [SM] Call stack trace:
L 03/09/2024 - 09:18:40: [SM]   [0] SetFailState
L 03/09/2024 - 09:18:40: [SM]   [1] Line 152, friendlyfire\entity.sp::Entity.CheckArrayBounds
L 03/09/2024 - 09:18:40: [SM]   [2] Line 158, friendlyfire\entity.sp::Entity.GetTeamInternal
L 03/09/2024 - 09:18:40: [SM]   [3] Line 141, friendlyfire\entity.sp::Entity.ResetTeam
L 03/09/2024 - 09:18:40: [SM]   [4] Line 301, friendlyfire\dhooks.sp::DHookCallback_CTFProjectile_Flare_Explode_Post
```

**Comment by Jugheadbomb** [comment]
According to previous message, there is another error spam with these dhook IDS (686 and 687), happens on map change
```cpp
L 03/09/2024 - 14:12:45: [friendlyfire.smx] Failed to remove dynamic hook (ID 687)
L 03/09/2024 - 14:12:45: [friendlyfire.smx] Failed to remove dynamic hook (ID 686)
```

**Comment by Mikusch** [comment]
Would need repro steps for the flare issue, as well as plugins that might
have caused this. Usually it's when other plugins modify attacker, which
breaks the whole system.

**Comment by NNinja1255** [comment]
Got this same issue whenever Zatoichi dueling.

**Comment by Mikusch** [comment]
> Got this same issue whenever Zatoichi dueling.

Could you provide more info? Is there any specific setup that allows me to reproduce this consistently? Can you rule out that this isn't other plugins interfering?

**Comment by NNinja1255** [comment]
It is literally just hitting people who have the zatoichi with the zatoichi

**Comment by Mikusch** [comment]
> It is literally just hitting people who have the zatoichi with the zatoichi. The only other plugin I have that modifies the attacker is the OnDamageTaken Hook, which I disabled and it didn't change anything.

Thanks, I can reproduce this. Could you submit a new issue so I can track this better? Hopefully the fix won't take too long.

**Comment by NNinja1255** [comment]
> Thanks, I can reproduce this. Could you submit a new issue so I can track this better? Hopefully the fix won't take too long.

#15
