### ISSUE TITLE
Can you removes player vs. player collisions?

### ISSUE THREAD

**Issue by HowToPlayMeow** [Mikusch/friendlyfire#9]
I use this plugin in jailbreak. And when the Warden launches Friendly Fire, it will "player block player" and that's the problem.

**Comment by Jugheadbomb** [comment]
@HowToPlayMeow you can comment out this line in https://github.com/Mikusch/friendlyfire/blob/master/addons/sourcemod/scripting/friendlyfire/convars.sp#L43 and recompile

**Comment by HowToPlayMeow** [comment]
> @HowToPlayMeowคุณสามารถแสดงความคิดเห็นในบรรทัดนี้ใน[https://github.com/Mikusch/Friendlyfire/blob/master/addons/sourcemod/scripting/Friendlyfire/convars.sp#L43](https://github.com/Mikusch/friendlyfire/blob/master/addons/sourcemod/scripting/friendlyfire/convars.sp#L43)และคอมไพล์ใหม่

It works. Thank you. :3

**Comment by HowToPlayMeow** [comment]
> @HowToPlayMeow you can comment out this line in https://github.com/Mikusch/friendlyfire/blob/master/addons/sourcemod/scripting/friendlyfire/convars.sp#L43 and recompile

It works. Thank you.

**Comment by Mikusch** [comment]
Hello, I know you've closed this already, but I've added a new convar `sm_friendlyfire_avoidteammates` (def. `0`) that allows you to configure player vs. player collisions on the same team without having to edit the plugin yourself. Set it to `1` to get the desired result.

**Comment by HowToPlayMeow** [comment]
> Hello, I know you've closed this already, but I've added a new convar `sm_friendlyfire_avoidteammates` (def. "0") in [1.2.3](https://github.com/Mikusch/friendlyfire/releases/tag/1.2.3) that allows you to configure player vs. player collisions on the same team without having to edit the plugin yourself. Set it to "1" to get the desired result.

I tested it and it works. Thank you for the update. :3
